---
title: "Question 3 - Dan"
author: "Dan Nolte"
date: "11/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
```

```{r}
# Load data
data = read.csv("cleaneddata.csv")

# TODO - consider measuring injuries in a different way, and incorporating sensitivities

# Generate data for Plots 1-3, Step 1
data1 = data %>% 
  drop_na(num_games_injured, num_games_missing) %>%
  filter(year < 2021) %>% 
  mutate(
    injury_class_2 = ifelse(num_games_missing > 0, 1, 0),
  ) %>% 
  group_by(year, full_team) %>% 
  summarize(
    injuries_class_2 = sum(injury_class_2),
    ) %>% 
  group_by(full_team) %>% 
  mutate(
    cumsum_injuries_class_2 = cumsum(injuries_class_2),
  )

# Generate data for Plots 1-3, Step 2
data2 = data1 %>% 
  group_by(full_team) %>% 
  summarize(
    total_injuries_class_2 = sum(injuries_class_2),
    median_injuries_class_2 = median(injuries_class_2),
    max_injuries_class_2 = max(injuries_class_2),
  )

# Join data from Step 1 and Step 2
data_for_plots = left_join(data1, data2, by = "full_team")

# Plot 1
p1 = ggplot(data = data2, aes(x = total_injuries_class_2, y = reorder(full_team, total_injuries_class_2))) +
  geom_col() + 
  theme_economist() + 
  xlab("Total Injuries (Class 2)") +
  ylab(element_blank()) +
  ggtitle("Total Injuries (Class 2) by Team, 2009-2020")
p1

# Plot 2
p2 = ggplot(data = data2, aes(x = max_injuries_class_2, y = reorder(full_team, max_injuries_class_2))) +
  geom_col() + 
  theme_economist() + 
  xlab("Total Injuries (Class 2)") +
  ylab(element_blank()) +
  ggtitle("Max Injuries in a Single Season, 2009-2020")
p2

# Plot 3
p3 = ggplot(data = data_for_plots, aes(x = injuries_class_2, y = reorder(full_team, median_injuries_class_2))) +
  geom_boxplot() + 
  theme_economist() + 
  xlab("Injuries Per Year") +
  ylab(element_blank()) +
  ggtitle("Injuries Per Year (2009-2020), by Team")
p3

# Plot 4
p4 = ggplot(data = data_for_plots, aes(x = year, y = full_team)) +
  geom_tile(aes(fill = injuries_class_2), color = "white") + 
  scale_fill_distiller(palette = "YlGnBu", direction = 1) +
  xlab("Year") +
  ylab(element_blank()) +
  ggtitle("Injuries by Team") +
  theme_economist() +
  theme(legend.position = "right") + 
  labs(fill = "Injuries")
p4


# Poisson Regression Analysis
p5 = ggplot(data = data_for_plots, aes(x=injuries_class_2)) +
  geom_histogram(binwidth = 2) +
  theme_economist()
p5

# TBD - estimate parameters, test assumptions, run and interpret Poisson regression
```