---
title: "Trends In Injuries Over Time"
author: "Lauren Mock"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(ggplot2)
```


## Read in and clean injury data

```{r}
injuries <- read.csv("Data/all_injuries_clean.csv", stringsAsFactors = FALSE)

# add column for total injuries
injuries <- injuries %>%
  mutate(all_injuries = select(injuries, c("head", "shoulder", "upper_torso", "lower_torso", 
                                           "arm", "hand", "leg", "foot")) %>% rowSums)

# filter out 2021 (partial data for this year)
injuries <- injuries %>% filter(year != 2021)
```


## Injuries per Season

```{r}
# create summarized table
time_series <- injuries %>%
  group_by(year) %>%
  summarize(all_injuries = sum(all_injuries))

# plot
time_series %>%
  ggplot(aes(x = year, y = all_injuries)) +
  geom_line() +
  ggtitle("Injuries per Season") +
  xlab("Year") +
  ylab("Total Number of Injuries") +
  ylim(0, 2800)
```

### As Boxplots

```{r}
injuries %>%
  ggplot(aes(x = as.factor(year), y = all_injuries)) +
  geom_boxplot() +
  ggtitle("Distribution of Number of Injuries per Player") +
  xlab("Year") +
  ylab("Injuries per Season per Player")
```


### Injuries per Season by Team

```{r}
# create summarized table
time_series_teams <- injuries %>%
  group_by(year, team) %>%
  summarize(all_injuries = sum(all_injuries))

# plot
time_series_teams %>%
  ggplot(aes(x = year, y = all_injuries, color = team)) +
  geom_line() +
  ggtitle("Injuries per Season by Team") +
  xlab("Year") +
  ylab("Total Number of Injuries") +
  ylim(0, 175)
```

## Concussions per Season

```{r}
# create summarized tables
concussions <- injuries %>%
  group_by(year) %>%
  summarize(head = sum(head))

# plot
concussions %>%
  ggplot(aes(x = year, y = head)) +
  geom_line() +
  ggtitle("Concussions per Season") +
  xlab("Year") +
  ylab("Total Number of Injuries") +
  ylim(0, 300)
```

### Concussions per Season by Team

```{r}
concussions_team <- injuries %>%
  group_by(year, team) %>%
  summarize(head = sum(head))


concussions_team %>%
  ggplot(aes(x = year, y = head, color = team)) +
  geom_line() +
  ggtitle("Concussions per Season") +
  xlab("Year") +
  ylab("Total Number of Injuries") +
  ylim(0, 20)
```


## All Injury Types over Time

```{r}
# gather into long format
gathered <- injuries %>%
  gather(key = broad_injury, value = broad_count, c("head", "shoulder", "upper_torso", "lower_torso", 
                                           "arm", "hand", "leg", "foot"))
# create summary table
gathered <- gathered %>%
  group_by(year, broad_injury) %>%
  summarise(broad_count = sum(broad_count))

# plot
gathered %>%
  ggplot(aes(x = year, y = broad_count, color = broad_injury)) +
  geom_line() +
  ggtitle("Injuries per Season by Type") +
  xlab("Year") +
  ylab("Injuries per Season (log scale)") +
  scale_y_log10()
```

### ...as barplots

```{r}
gathered %>%
  ggplot(aes(x = year, y = broad_count, fill = broad_injury)) +
  geom_bar(stat = "identity") + 
  ggtitle("Injury Type by Year") +
  xlab("Year") +
  ylab("Number of Injuries") +
  labs(fill = "Injury Type") +
  scale_color_hue(labels = c("Arm", "Foot", "Hand", "Head", "Leg", "Lower Torso", 
                                "Shoulder", "Upper Torso"))

gathered %>%
  ggplot(aes(x = year, y = broad_count, fill = broad_injury)) +
  geom_bar(stat = "identity", position = "dodge") + 
  ggtitle("Injury Type by Year") +
  xlab("Year") +
  ylab("Number of Injuries") +
  labs(fill = "Injury Type") +
  scale_color_hue(labels = c("Arm", "Foot", "Hand", "Head", "Leg", "Lower Torso", 
                                "Shoulder", "Upper Torso"))
```

## Check Number of Players in Dataset

```{r}
injuries %>%
  group_by(year) %>%
  summarize(players = n()) %>%
  ggplot(aes(x = year, y = players)) +
  geom_line() +
  ylim(0, 1600) +
  ggtitle("Number of Players in Dataset Each Season")

```

## Games missed/played injured per season

```{r}
### games missed
games_missed <- injuries %>%
  group_by(year) %>%
  summarize(avg_games_missed = mean(num_games_missing))

games_missed %>%
  ggplot(aes(x = year, y = avg_games_missed)) +
  geom_line() +
  ylim(0, 7) +
  ggtitle("Games Missed Due to Injury") +
  xlab("Season") +
  ylab("Games Missed")


### games injured
games_injured <- injuries %>%
  group_by(year) %>%
  summarize(avg_games_injured = mean(num_games_injured))

games_injured %>%
  ggplot(aes(x = year, y = avg_games_injured)) +
  geom_line() +
  ylim(0, 7) +
  ggtitle("Games Injured") +
  xlab("Season") +
  ylab("Games Injured")
```


## Can we use Poisson regression to predict # of injuries?

```{r, fig.height = 2, fig.width=12}
injuries %>%
  ggplot(aes(x = all_injuries)) + 
  geom_histogram(binwidth = 1, col = "black", fill = "skyblue")

injuries %>%
  ggplot(aes(x = all_injuries)) + 
  geom_histogram(binwidth = 1, col = "black", fill = "skyblue") +
  facet_grid(. ~ year)
```


### Try fitting Poisson model

```{r}
poisson_fit <- glm(all_injuries ~ as.factor(year), family = poisson, data = time_series)
summary(poisson_fit)
```

